#!/bin/bash

# Function to find the highest python version
find_python() {
    for version in 3 3.9 3.8 3.7 3.6 3.5 2.7; do
        if command -v python$version &>/dev/null; then
            echo "python$version"
            return
        fi
    done
    echo "No suitable Python interpreter found" >&2
    exit 1
}

# Pull down changes...
git pull

# Detect the current python binary or find the highest version available
PYTHON_BIN=$(command -v python || find_python)

# Change to the lib directory and run the tests
(cd src/lib && $PYTHON_BIN run_all_tests.py)

# Capture the exit status of the Python script
exit_status=$?

# Check if the Python script exited with a non-zero exit status
if [ $exit_status -ne 0 ]; then
    echo "Tests failed with exit status $exit_status, aborting..."
    exit $exit_status
fi

echo "All tests passed. Running inventory.py..."
$PYTHON_BIN src/lib/inventory.py