#!/bin/bash

# Define variables
REMOTE_HOST="10.100.5.154"        	# Replace with your remote host
REMOTE_PATH="/root"    			# Replace with the desired remote path

# Run debuild command
debuild -us -uc -b

# Get the package name and version from the .changes file
PACKAGE_NAME=$(dpkg-parsechangelog | grep '^Source:' | awk '{print $2}')
PACKAGE_VERSION=$(dpkg-parsechangelog | grep '^Version:' | awk '{print $2}')
DEB_FILE="${PACKAGE_NAME}_${PACKAGE_VERSION}_all.deb"

# Check if the .deb file was created
if [ -f "../$DEB_FILE" ]; then
    # SCP the file to the remote host
    scp "../$DEB_FILE" "$REMOTE_HOST:$REMOTE_PATH"
    echo "File $DEB_FILE copied to $REMOTE_HOST:$REMOTE_PATH successfully."
else
    echo "Error: .deb file not found. Please check if the debuild command succeeded."
    exit 1
fi

echo "Uninstalling package on remote host"
ssh $REMOTE_HOST dpkg -r xo-ansible-inventory-manager

echo "Installing package on remote host"
ssh $REMOTE_HOST dpkg -i $REMOTE_PATH/$DEB_FILE
